
all:
  hosts:
  children:
    webservers:
      hosts:
        web1:
          ansible_user: root
          ansible_host: 192.168.157.57
        web2:
          ansible_user: root
          ansible_host: 192.168.157.29
    db:
      hosts:
        db1:
          ansible_user: sfleury
          ansible_host: 192.168.157.10
        db2:
          ansible_user: sfleury
          ansible_host: 192.168.157.187
    syslog:
      hosts:
        syslog:
          ansible_user: sfleury
          ansible_host: 192.168.157.251
    backup:
      hosts:
        backup:
          ansible_user: sfleury
          ansible_host: 192.168.157.194

