
all:
  hosts:
  children:
    webservers:
      hosts:
        node1:
          ansible_user: root
        node2:
          ansible_user: root
    db:
      hosts:
        node3:
          ansible_user: root
        node4:
          ansible_user: root

